
---
kind: BuildingKind
spec:
  category: factory
  name: "Bards Concert Hall"
  description: sick tunes mate
  model: 12-14
  color: 3
  contract:
    file: ../contracts/BardsConcertHall.sol
  plugin:
    file: ../js/BardsConcertHall.js
  materials:
    - name: Red Goo
      quantity: 10
    - name: Green Goo
      quantity: 10
    - name: Blue Goo
      quantity: 10
  inputs:
    - name: Green Goo
      quantity: 100
    - name: Blue Goo
      quantity: 50
    - name: Red Goo
      quantity: 50
  outputs:
    - name: Taylor Swifts Guitar
      quantity: 1

---
kind: Item
spec:
  name: Taylor Swifts Guitar
  icon: 19-35
  goo:
    red: 25
    green: 50
    blue: 25
  stackable: false
