---
kind: BuildingKind
spec:
  category: factory
  name: Barrier
  description: Protect your Castle from attacks, needs a construction hammer to build
  model: 01-08
  color: 3
  contract:
    file: ../contracts/Barrier.sol
  plugin:
    file: ../js/Barrier.js
  materials:
    - name: Red Goo
      quantity: 10
    - name: Green Goo
      quantity: 60
    - name: Blue Goo
      quantity: 60
  inputs:
    - name: Red Goo
      quantity: 2
    - name: Green Goo
      quantity: 2
    - name: Blue Goo
      quantity: 2
  outputs:
    - name: spam
      quantity: 1

---
kind: Item
spec:
  name: spam
  icon: 22-170
  goo:
    red: 1
    green: 1
    blue: 1
  stackable: false
